### ISSUE TITLE
BAC-002 support

### ISSUE THREAD

**Issue by gtudan** [maccoylton/esp-homekit-wired-thermostat#2]
Hi, this looks really promising and I'm eager to try it out!

Does this software only support the BHT-002, or will similar devices like the BAC-002 also work?

**Comment by maccoylton** [comment]
It should be possible, the protocol would need modified potentially.  I don't have such a device, so If you have a device I can guide you on changes necessary, process would be slow though as the manufacturers don't always stick strictly to th eprotovcla and there is a bit of trial and error involved.

**Comment by shrieke-gee** [comment]
Hi there, this is exactly what I was looking for and thank you for making it available!

I was wondering if you could Kindly point me in the right direction on how to flash firmware to BHT-002?

i.e.
What equipment is required and where to solder the wires?

Any help would be appreciated, thank you.

**Comment by maccoylton** [comment]
> Hi there, this is exactly what I was looking for and thank you for making it available!
> 
> I was wondering if you could Kindly point me in the right direction on how to flash firmware to BHT-002?
> 
> i.e.
> What equipment is required and where to solder the wires?
> 
> Any help would be appreciated, thank you.

I added an image to the Wiki to show the connections for flashing. I assume you know how to flash an ESP .

**Comment by shrieke-gee** [comment]
Not really, but I am looking into it. Would you say that this is a reasonable guide?
[https://www.instructables.com/ESP8266-WiFi-Module-for-Dummies/](url)

**Comment by maccoylton** [comment]
Did you checkout the wiki:- https://github.com/maccoylton/esp-homekit-wired-thermostat/wiki 
Take a look and ask any questions you still might have
