### ISSUE TITLE
printf log

### ISSUE THREAD

**Issue by danilkorotkov** [maccoylton/esp-homekit-wired-thermostat#3]
hi, does MCU unit ignore serial log output?
I started to build homekit firmware for Avatto ME81H thermostat and worried about debug log.
Also I didn't find apps to listen broadcast udp log for mac os.

**Comment by maccoylton** [comment]
The communications between the MCU and the ESP is via the serial port, so you can't use serial port for logging otherwise you get unpredictable results. My firmware sends login over UDP by redirecting printf

**Comment by maccoylton** [comment]
The client is part of the udplogger which can be found at https://github.com/HomeACcessoryKid/UDPlogger

**Comment by danilkorotkov** [comment]
thank you
but im using arduino esp-idf, not rtos
so i redifined printf with 2 macro for udp broadcast

```
#include <WiFiUdp.h>
WiFiUDP Udp;
IPAddress broadcastIp;
uint16_t  bPort = 8888;
#include "wifi_info.h"

char buffer[256]; 
uint32_t counter = 1;

#define LOG_D(fmt, ...)  if (WiFi.isConnected()) { \
  Udp.beginPacket(broadcastIp,bPort); \
  sprintf_P(buffer, PSTR(fmt "\n"), ##__VA_ARGS__); \
  Udp.write(buffer); \
  Udp.endPacket(); \
  }

#define printf(fmt, ...) LOG_D(fmt, ##__VA_ARGS__)

void setup() {
  Serial.begin(115200);
  wifi_connect(); // in wifi_info.h
  IPAddress broadcastIp = WiFi.localIP(); //(10,0,1,22);
  broadcastIp[3] = 255;
  
}

void loop() {
  LOG_D("UDP log: %d", counter);
  printf("printf log: %d", counter);
  counter++;
  delay(10000);

}
```

**Comment by maccoylton** [comment]
Assume you have all you need so closing.
