### ISSUE TITLE
Device won't starts after flash

### ISSUE THREAD

**Issue by GPL71** [maccoylton/esp-homekit-wired-thermostat#5]
Hello ...
just flashed a BHT002GA wifi as your project.

Downloaded main.bin file and renamed in bootloader.bin
Below the flsah command modified respect your steps I've used

esptool.py -p /dev/tty.SLAB_USBtoUART --baud 230400 write_flash -fs 1MB -fm dout -ff 40m 0x0 bootloaer.bin

At the end of flash I received the WARNIG below

esptool.py v3.0
Serial port /dev/tty.SLAB_USBtoUART
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 8c:aa:b5:46:63:ce
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 230400
Changed.
Configuring flash size...
Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.
Compressed 486100 bytes to 341651...
Wrote 486100 bytes (341651 compressed) at 0x00000000 in 15.1 seconds (effective 258.0 kbit/s)...
Hash of data verified.

Result was ndevice won't start an no AP

Could you help me?
Thank you

**Comment by GPL71** [comment]
Solved using a old version of otaboot, rboot and blank_config files...

Now I have another problem
Tried add thermostat in HOME but not is possible for an error.
It no possible try add again because HOME now is blind

**Comment by GPL71** [comment]
Solved ... the right commad to flash the board is 

esptool.py --port /dev/tty.SLAB_USBtoUART write_flash --flash_size detect --flash_mode dout --flash_freq 40m 0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin

You'll needed the following files:
otaboot.bin
rboot.bin
blank_config

**Comment by maccoylton** [comment]
For reference this is all covered in the Wiki.
