### ISSUE TITLE
Help with firmware

### ISSUE THREAD

**Issue by megaj07** [maccoylton/esp-homekit-wired-thermostat#6]
Hello. I'm trying to flash the thermostat. I downloaded the bootloader.bin file from the maccoylton/esp-homekit-motion-sensor theme, the LCM-XXXX access point appeared, connected, did everything according to the wiki instructions:
-select your WiFi by clicking on it
-enter your WiFi password
-enter the GitHub directory -maccoylton/esp-homekit-wired-thermostat
-enter filename -main.bin.
-LED GPIO should be set to 13
-click the join button
After that, the access point disappears and that's it, then nothing happens. The device does not appear in Homekit. Maybe some soap? Thank you in advance!

**Comment by maccoylton** [comment]
Those set get the firmware loaded and the device connected to your wifi, after that you need to go into the Home app and go through the process to add a new accessory.

**Comment by megaj07** [comment]
In the Home application, as usual, I try to add a new device with the code 1111-1111, but the new device does not appear

**Comment by maccoylton** [comment]
What exactly happened. When you try to add a new device does it show up and the you get to enter the pin?

**Comment by megaj07** [comment]
Hello. Thanks for the answer. Device not showing up in Homekit for pairing

**Comment by megaj07** [comment]
For the firmware, the esp module was soldered. Then I flashed bootloader.bin. Then I connected it to the access point both on the dismantled module and on the assembled thermostat. pairing does not occur
